/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_dfki_covida_NativeInterface */

#ifndef _Included_de_dfki_covida_NativeInterface
#define _Included_de_dfki_covida_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_dfki_covida_NativeInterface
 * Method:    onVideoOpened
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_dfki_covida_NativeInterface_onVideoOpened
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_dfki_covida_NativeInterface
 * Method:    onVideoClosed
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_dfki_covida_NativeInterface_onVideoClosed
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_dfki_covida_NativeInterface
 * Method:    onImageOpened
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_dfki_covida_NativeInterface_onImageOpened
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_dfki_covida_NativeInterface
 * Method:    onImageClosed
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_dfki_covida_NativeInterface_onImageClosed
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_dfki_covida_NativeInterface
 * Method:    circleAnnotation
 * Signature: (Ljava/lang/String;Ljava/lang/String;JJFFF[Ljava/awt/Point;)V
 */
JNIEXPORT void JNICALL Java_de_dfki_covida_NativeInterface_circleAnnotation
  (JNIEnv *, jobject, jstring, jstring, jlong, jlong, jfloat, jfloat, jfloat, jobjectArray);

/*
 * Class:     de_dfki_covida_NativeInterface
 * Method:    lineAnnotation
 * Signature: (Ljava/lang/String;Ljava/lang/String;JJFFFF[Ljava/awt/Point;)V
 */
JNIEXPORT void JNICALL Java_de_dfki_covida_NativeInterface_lineAnnotation
  (JNIEnv *, jobject, jstring, jstring, jlong, jlong, jfloat, jfloat, jfloat, jfloat, jobjectArray);

/*
 * Class:     de_dfki_covida_NativeInterface
 * Method:    polygonAnnotation
 * Signature: (Ljava/lang/String;Ljava/lang/String;JJ[Ljava/awt/Point;)V
 */
JNIEXPORT void JNICALL Java_de_dfki_covida_NativeInterface_polygonAnnotation
  (JNIEnv *, jobject, jstring, jstring, jlong, jlong, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
