/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_dfki_covida_NativeInterface_ShutdownHook */

#ifndef _Included_de_dfki_covida_NativeInterface_ShutdownHook
#define _Included_de_dfki_covida_NativeInterface_ShutdownHook
#ifdef __cplusplus
extern "C" {
#endif
#undef de_dfki_covida_NativeInterface_ShutdownHook_MIN_PRIORITY
#define de_dfki_covida_NativeInterface_ShutdownHook_MIN_PRIORITY 1L
#undef de_dfki_covida_NativeInterface_ShutdownHook_NORM_PRIORITY
#define de_dfki_covida_NativeInterface_ShutdownHook_NORM_PRIORITY 5L
#undef de_dfki_covida_NativeInterface_ShutdownHook_MAX_PRIORITY
#define de_dfki_covida_NativeInterface_ShutdownHook_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
