// stdafx.cpp : Quelldatei, die nur die Standard-Includes einbindet.
// Win7InputDeviceAdapter.pch ist der vorkompilierte Header.
// stdafx.obj enthält die vorkompilierten Typinformationen.

#include "stdafx.h"


/* DO NOT EDIT THIS FILE - it is machine generated */

