<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<profile name="default" pageid="0.0.0.0">
    <modeareas>
        <modearea name="eee-slate">
            <area>
                <x>
                    <value>0</value>
                    <value>1280</value>
                    <value>1280</value>
                    <value>0</value>
                </x>
                <y>
                    <value>0</value>
                    <value>0</value>
                    <value>800</value>
                    <value>800</value>
                </y>
            </area>
            <modeconfig>
                <gesturerecognition>
                    <enabled>true</enabled>
                </gesturerecognition>
                <hwrconfiguration>
                    <dict>
                        <dictionary>en_GB-ak-cur.res</dictionary>
                        <linguistic>en_GB-lk-text.res</linguistic>
						<wordlist>radlex-eng.wlist</wordlist>
                        <locale>eng</locale>
                    </dict>
                    <orientationCorrection>true</orientationCorrection>
                    <disableMultipleLines>false</disableMultipleLines>
                    <wordCandidateListSize>10</wordCandidateListSize>
                </hwrconfiguration>
                <shapedetection>
                    <combineStrokes>false</combineStrokes>
                    <enabled>true</enabled>
                    <weightCircle>0</weightCircle>
                    <weightCurvedArrow>0</weightCurvedArrow>
                    <weightEllipticArc>0</weightEllipticArc>
                    <weightEllispe>0</weightEllispe>
                    <weightLine>0</weightLine>
                    <weightParallelogram>0</weightParallelogram>
                    <weightRectangle>0</weightRectangle>
                    <weightRhombus>0</weightRhombus>
                    <weightStroke>0</weightStroke>
                    <weightTriangle>0</weightTriangle>
                </shapedetection>
                <trainingData>training-data</trainingData>
            </modeconfig>
        </modearea>
    </modeareas>
</profile>
