<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<profile name="default" pageid="0.0.0.0">
    <modeareas>
        <modearea name="eee-slate">
            <area>
                <x>
                    <value>0</value>
                    <value>1280</value>
                    <value>1280</value>
                    <value>0</value>
                </x>
                <y>
                    <value>0</value>
                    <value>0</value>
                    <value>800</value>
                    <value>800</value>
                </y>
            </area>
            <modeconfig>
                <gesturerecognition>
                    <enabled>false</enabled>
                </gesturerecognition>
                <hwrconfiguration>
                    <dict>
                        <dictionary>en_GB-ak-cur.res</dictionary>
                        <linguistic>en_GB-lk-text.res</linguistic>
						<wordlist>radlex-eng.wlist</wordlist>
                        <locale>eng</locale>
                    </dict>
                    <orientationCorrection>true</orientationCorrection>
                    <disableMultipleLines>false</disableMultipleLines>
                    <wordCandidateListSize>10</wordCandidateListSize>
                </hwrconfiguration>
                <shapedetection>
                    <combineStrokes>false</combineStrokes>
                    <enabled>true</enabled>
                    <weightCircle>1</weightCircle>
                    <weightCurvedArrow>1</weightCurvedArrow>
                    <weightEllipticArc>1</weightEllipticArc>
                    <weightEllispe>1</weightEllispe>
                    <weightLine>1</weightLine>
                    <weightParallelogram>1</weightParallelogram>
                    <weightRectangle>1</weightRectangle>
                    <weightRhombus>1</weightRhombus>
                    <weightStroke>1</weightStroke>
                    <weightTriangle>1</weightTriangle>
                </shapedetection>
                <trainingData>../covida-res/training-data</trainingData>
            </modeconfig>
        </modearea>
    </modeareas>
</profile>
