<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<profile name="default" pageid="70.0.4.20">
    <modeareas>
        <modearea name="default">
            <area>
                <x>
                    <value>0</value>
                    <value>1280</value>
                    <value>1280</value>
                    <value>0</value>
                </x>
                <y>
                    <value>0</value>
                    <value>0</value>
                    <value>800</value>
                    <value>800</value>
                </y>
            </area>
            <modeconfig>
<hwrconfiguration>

	   <dict>
            <linguistic>en_US-lk-text.res</linguistic>
            <!--<linguistic>furniture-lexicon.res</linguistic>-->
        	<locale>eng</locale>
	    </dict>
	    <dict>
		   <dictionary>en_US-ak-cur.res</dictionary>
		   <linguistic>en_US-lk-text.res</linguistic>
            <!--<linguistic>metric-lexicon.res</linguistic>-->
        	<locale>eng</locale>
	    </dict>
		<orientationCorrection>true</orientationCorrection>
		<disableMultipleLines>false</disableMultipleLines>
		<wordCandidateListSize>10</wordCandidateListSize>
	</hwrconfiguration>
                <shapedetection>
                    <combineStrokes>false</combineStrokes>
                    <enabled>true</enabled>
                    <weightCircle>1.0</weightCircle>
                    <weightCurvedArrow>1.0</weightCurvedArrow>
                    <weightEllipticArc>1.0</weightEllipticArc>
                    <weightEllispe>1.0</weightEllispe>
                    <weightLine>1.0</weightLine>
                    <weightParallelogram>1.0</weightParallelogram>
                    <weightRectangle>1.0</weightRectangle>
                    <weightRhombus>1.0</weightRhombus>
                    <weightStroke>1.0</weightStroke>
                    <weightTriangle>1.0</weightTriangle>
                </shapedetection>
                <trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
            </modeconfig>
        </modearea>
    </modeareas>
</profile>
