<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<profile name="EEE Slate" pageid="0.0.0.0">
    <modeareas>
        <modearea name="EEE Slate">
            <area>
                <x>
                    <value>0</value>
                    <value>1280</value>
                    <value>1280</value>
                    <value>0</value>
                </x>
                <y>
                    <value>0</value>
                    <value>0</value>
                    <value>800</value>
                    <value>800</value>
                </y>
            </area>
            <modeconfig>
                <gesturerecognition>
                    <enabled>true</enabled>
                </gesturerecognition>
                <hwrconfiguration>
                    <dict>
                        <dictionary>en_US-ak-cur.res</dictionary>
                        <linguistic>en_US-lk-text.res</linguistic>
                        <locale>eng</locale>
                    </dict>
                    <orientationCorrection>true</orientationCorrection>
                    <disableMultipleLines>false</disableMultipleLines>
                    <wordCandidateListSize>10</wordCandidateListSize>
                </hwrconfiguration>
                <shapedetection>
                    <combineStrokes>false</combineStrokes>
                    <enabled>false</enabled>
                    <weightCircle>1.0</weightCircle>
                    <weightCurvedArrow>1.0</weightCurvedArrow>
                    <weightEllipticArc>1.0</weightEllipticArc>
                    <weightEllispe>1.0</weightEllispe>
                    <weightLine>1.0</weightLine>
                    <weightParallelogram>1.0</weightParallelogram>
                    <weightRectangle>1.0</weightRectangle>
                    <weightRhombus>1.0</weightRhombus>
                    <weightStroke>1.0</weightStroke>
                    <weightTriangle>1.0</weightTriangle>
                </shapedetection>
                <trainingData>src/main/resources/training-data/</trainingData>
            </modeconfig>
        </modearea>
    </modeareas>
</profile>
