<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<profile name="mammography-page1" pageid="72.0.7.2">
	<modeareas>
		<modearea name="head-hwr">
			<area>
				<x>
					<value>56</value>
					<value>701</value>
					<value>687</value>
					<value>701</value>
				</x>
				<y>
					<value>206</value>
					<value>206</value>
					<value>456</value>
					<value>456</value>
				</y>
			</area>
			<modeconfig>
					<hwrconfiguration>
					<dict>
						<dictionary>en_US-ak-cur.res</dictionary>
						<linguistic>en_US-lk-text.res</linguistic>
						<locale>eng</locale>
					</dict>
					<disableMultipleLines>false</disableMultipleLines>
					<wordCandidateListSize>10</wordCandidateListSize>
					<orientationCorrection>true</orientationCorrection>
				</hwrconfiguration>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>
		<modearea name="klinbef-hwr-left">
			<area>
				<x>
					<value>504</value>
					<value>687</value>
					<value>687</value>
					<value>504</value>
				</x>
				<y>
					<value>466</value>
					<value>466</value>
					<value>483</value>
					<value>483</value>
				</y>
			</area>
			<modeconfig>
					<hwrconfiguration>
					<dict>
						<dictionary>en_US-ak-cur.res</dictionary>
						<linguistic>en_US-lk-text.res</linguistic>
						<locale>eng</locale>
					</dict>
					<disableMultipleLines>false</disableMultipleLines>
					<wordCandidateListSize>10</wordCandidateListSize>
					<orientationCorrection>true</orientationCorrection>
				</hwrconfiguration>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>
		<modearea name="klinbef-hwr-right">
			<area>
				<x>
					<value>56</value>
					<value>243</value>
					<value>243</value>
					<value>56</value>
				</x>
				<y>
					<value>466</value>
					<value>466</value>
					<value>483</value>
					<value>483</value>
				</y>
			</area>
			<modeconfig>
					<hwrconfiguration>
					<dict>
						<dictionary>en_US-ak-cur.res</dictionary>
						<linguistic>en_US-lk-text.res</linguistic>
						<locale>eng</locale>
					</dict>
					<disableMultipleLines>false</disableMultipleLines>
					<wordCandidateListSize>10</wordCandidateListSize>
					<orientationCorrection>true</orientationCorrection>
				</hwrconfiguration>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>
		<modearea name="klinbef-birad-left">
			<area>
				<x>
					<value>504</value>
					<value>577</value>
					<value>577</value>
					<value>504</value>
				</x>
				<y>
					<value>533</value>
					<value>533</value>
					<value>640</value>
					<value>640</value>
				</y>
			</area>
			<modeconfig>
				<shapedetection>
					<combineStrokes>false</combineStrokes>
					<enabled>true</enabled>
					<weightCircle>1.0</weightCircle>
					<weightCurvedArrow>0.0</weightCurvedArrow>
					<weightEllipticArc>0.0</weightEllipticArc>
					<weightEllispe>1.0</weightEllispe>
					<weightLine>0.0</weightLine>
					<weightParallelogram>0.0</weightParallelogram>
					<weightRectangle>1.0</weightRectangle>
					<weightRhombus>0.0</weightRhombus>
					<weightStroke>0.0</weightStroke>
					<weightTriangle>0.0</weightTriangle>
				</shapedetection>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>
		<modearea name="klinbef-birad-right">
			<area>
				<x>
					<value>56</value>
					<value>133</value>
					<value>133</value>
					<value>56</value>
				</x>
				<y>
					<value>533</value>
					<value>533</value>
					<value>640</value>
					<value>640</value>
				</y>
			</area>
			<modeconfig>
				<shapedetection>
					<combineStrokes>false</combineStrokes>
					<enabled>true</enabled>
					<weightCircle>1.0</weightCircle>
					<weightCurvedArrow>0.0</weightCurvedArrow>
					<weightEllipticArc>0.0</weightEllipticArc>
					<weightEllispe>1.0</weightEllispe>
					<weightLine>0.0</weightLine>
					<weightParallelogram>0.0</weightParallelogram>
					<weightRectangle>1.0</weightRectangle>
					<weightRhombus>0.0</weightRhombus>
					<weightStroke>0.0</weightStroke>
					<weightTriangle>0.0</weightTriangle>
				</shapedetection>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>
		<modearea name="klinbef-image">
			<area>
				<x>
					<value>253</value>
					<value>480</value>
					<value>480</value>
					<value>253</value>
				</x>
				<y>
					<value>470</value>
					<value>470</value>
					<value>633</value>
					<value>633</value>
				</y>
			</area>
			<modeconfig>
				<shapedetection>
					<combineStrokes>false</combineStrokes>
					<enabled>true</enabled>
					<weightCircle>1.0</weightCircle>
					<weightCurvedArrow>0.0</weightCurvedArrow>
					<weightEllipticArc>0.0</weightEllipticArc>
					<weightEllispe>1.0</weightEllispe>
					<weightLine>0.0</weightLine>
					<weightParallelogram>0.0</weightParallelogram>
					<weightRectangle>1.0</weightRectangle>
					<weightRhombus>0.0</weightRhombus>
					<weightStroke>0.0</weightStroke>
					<weightTriangle>0.0</weightTriangle>
				</shapedetection>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>
		<modearea name="mrt-image">
			<area>
				<x>
					<value>253</value>
					<value>480</value>
					<value>480</value>
					<value>253</value>
				</x>
				<y>
					<value>676</value>
					<value>676</value>
					<value>840</value>
					<value>840</value>
				</y>
			</area>
			<modeconfig>
				<shapedetection>
					<combineStrokes>false</combineStrokes>
					<enabled>true</enabled>
					<weightCircle>1.0</weightCircle>
					<weightCurvedArrow>0.0</weightCurvedArrow>
					<weightEllipticArc>0.0</weightEllipticArc>
					<weightEllispe>1.0</weightEllispe>
					<weightLine>0.0</weightLine>
					<weightParallelogram>0.0</weightParallelogram>
					<weightRectangle>1.0</weightRectangle>
					<weightRhombus>0.0</weightRhombus>
					<weightStroke>0.0</weightStroke>
					<weightTriangle>0.0</weightTriangle>
				</shapedetection>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>
		<modearea name="mrt-shapedetection-left">
			<area>
				<x>
					<value>500</value>
					<value>680</value>
					<value>680</value>
					<value>500</value>
				</x>
				<y>
					<value>703</value>
					<value>703</value>
					<value>906</value>
					<value>906</value>
				</y>
			</area>
			<modeconfig>
				<shapedetection>
					<combineStrokes>false</combineStrokes>
					<enabled>true</enabled>
					<weightCircle>1.0</weightCircle>
					<weightCurvedArrow>0.0</weightCurvedArrow>
					<weightEllipticArc>0.0</weightEllipticArc>
					<weightEllispe>1.0</weightEllispe>
					<weightLine>0.0</weightLine>
					<weightParallelogram>0.0</weightParallelogram>
					<weightRectangle>1.0</weightRectangle>
					<weightRhombus>0.0</weightRhombus>
					<weightStroke>0.0</weightStroke>
					<weightTriangle>0.0</weightTriangle>
				</shapedetection>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>
		<modearea name="mrt-shapedetection-right">
			<area>
				<x>
					<value>56</value>
					<value>233</value>
					<value>233</value>
					<value>56</value>
				</x>
				<y>
					<value>703</value>
					<value>703</value>
					<value>906</value>
					<value>906</value>
				</y>
			</area>
			<modeconfig>
				<shapedetection>
					<combineStrokes>false</combineStrokes>
					<enabled>true</enabled>
					<weightCircle>1.0</weightCircle>
					<weightCurvedArrow>0.0</weightCurvedArrow>
					<weightEllipticArc>0.0</weightEllipticArc>
					<weightEllispe>1.0</weightEllispe>
					<weightLine>0.0</weightLine>
					<weightParallelogram>0.0</weightParallelogram>
					<weightRectangle>1.0</weightRectangle>
					<weightRhombus>0.0</weightRhombus>
					<weightStroke>0.0</weightStroke>
					<weightTriangle>0.0</weightTriangle>
				</shapedetection>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>
		<modearea name="mrt-birads">
			<area>
				<x>
					<value>317</value>
					<value>417</value>
					<value>417</value>
					<value>317</value>
				</x>
				<y>
					<value>856</value>
					<value>856</value>
					<value>950</value>
					<value>950</value>
				</y>
			</area>
			<modeconfig>
				<shapedetection>
					<combineStrokes>false</combineStrokes>
					<enabled>true</enabled>
					<weightCircle>1.0</weightCircle>
					<weightCurvedArrow>0.0</weightCurvedArrow>
					<weightEllipticArc>0.0</weightEllipticArc>
					<weightEllispe>1.0</weightEllispe>
					<weightLine>0.0</weightLine>
					<weightParallelogram>0.0</weightParallelogram>
					<weightRectangle>1.0</weightRectangle>
					<weightRhombus>0.0</weightRhombus>
					<weightStroke>0.0</weightStroke>
					<weightTriangle>0.0</weightTriangle>
				</shapedetection>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>
		<modearea name="mrt-hwr-left">
			<area>
				<x>
					<value>660</value>
					<value>694</value>
					<value>694</value>
					<value>660</value>
				</x>
				<y>
					<value>816</value>
					<value>816</value>
					<value>960</value>
					<value>960</value>
				</y>
			</area>
			<modeconfig>
				<hwrconfiguration>
					<dict>
						<dictionary>en_US-ak-cur.res</dictionary>
						<linguistic>en_US-lk-text.res</linguistic>
						<locale>eng</locale>
					</dict>
					<disableMultipleLines>false</disableMultipleLines>
					<wordCandidateListSize>10</wordCandidateListSize>
					<orientationCorrection>true</orientationCorrection>
				</hwrconfiguration>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>
		<modearea name="mrt-hwr-right">
			<area>
				<x>
					<value>136</value>
					<value>250</value>
					<value>250</value>
					<value>136</value>
				</x>
				<y>
					<value>816</value>
					<value>816</value>
					<value>960</value>
					<value>960</value>
				</y>
			</area>
			<modeconfig>
				<hwrconfiguration>
					<dict>
						<dictionary>en_US-ak-cur.res</dictionary>
						<linguistic>en_US-lk-text.res</linguistic>
						<locale>eng</locale>
					</dict>
					<disableMultipleLines>false</disableMultipleLines>
					<wordCandidateListSize>10</wordCandidateListSize>
					<orientationCorrection>true</orientationCorrection>
				</hwrconfiguration>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>
	</modeareas>
</profile>