<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<profile name="mammography-form" pageid="72.0.7.1">
	<modeareas>
		<modearea name="sonography-image">
			<area>
				<x>
					<value>220</value>
					<value>460</value>
					<value>460</value>
					<value>220</value>
				</x>
				<y>
					<value>50</value>
					<value>50</value>
					<value>220</value>
					<value>220</value>
				</y>
			</area>
			<modeconfig>
				<shapedetection>
					<combineStrokes>false</combineStrokes>
					<enabled>true</enabled>
					<weightCircle>1.0</weightCircle>
					<weightCurvedArrow>0.0</weightCurvedArrow>
					<weightEllipticArc>0.0</weightEllipticArc>
					<weightEllispe>0.0</weightEllispe>
					<weightLine>1.0</weightLine>
					<weightParallelogram>0.0</weightParallelogram>
					<weightRectangle>0.0</weightRectangle>
					<weightRhombus>0.0</weightRhombus>
					<weightStroke>0.0</weightStroke>
					<weightTriangle>0.0</weightTriangle>
				</shapedetection>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>
		<modearea name="mammography-image">
			<area>
				<x>
					<value>260</value>
					<value>410</value>
					<value>410</value>
					<value>260</value>
				</x>
				<y>
					<value>370</value>
					<value>370</value>
					<value>710</value>
					<value>710</value>
				</y>
			</area>
			<modeconfig>
				<shapedetection>
					<combineStrokes>false</combineStrokes>
					<enabled>true</enabled>
					<weightCircle>1.0</weightCircle>
					<weightCurvedArrow>0.0</weightCurvedArrow>
					<weightEllipticArc>0.0</weightEllipticArc>
					<weightEllispe>0.0</weightEllispe>
					<weightLine>1.0</weightLine>
					<weightParallelogram>0.0</weightParallelogram>
					<weightRectangle>0.0</weightRectangle>
					<weightRhombus>0.0</weightRhombus>
					<weightStroke>0.0</weightStroke>
					<weightTriangle>0.0</weightTriangle>
				</shapedetection>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>		
		<modearea name="findings-sonography-right">
			<area>
				<x>
					<value>32</value>
					<value>220</value>
					<value>220</value>
					<value>32</value>
				</x>
				<y>
					<value>0</value>
					<value>0</value>
					<value>280</value>
					<value>280</value>
				</y>
			</area>
			<modeconfig>
				<hwrconfiguration>
					<dict>
						<dictionary>en_US-ak-cur.res</dictionary>
						<linguistic>en_US-lk-text.res</linguistic>
						<locale>eng</locale>
					</dict>
					<orientationCorrection>true</orientationCorrection>
					<disableMultipleLines>false</disableMultipleLines>
					<wordCandidateListSize>10</wordCandidateListSize>
				</hwrconfiguration>
				<shapedetection>
					<combineStrokes>false</combineStrokes>
					<enabled>true</enabled>
					<weightCircle>1.0</weightCircle>
					<weightCurvedArrow>0.0</weightCurvedArrow>
					<weightEllipticArc>0.0</weightEllipticArc>
					<weightEllispe>1.0</weightEllispe>
					<weightLine>1.0</weightLine>
					<weightParallelogram>0.0</weightParallelogram>
					<weightRectangle>1.0</weightRectangle>
					<weightRhombus>0.0</weightRhombus>
					<weightStroke>0.0</weightStroke>
					<weightTriangle>0.0</weightTriangle>
				</shapedetection>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>		
		<modearea name="findings-sonography-right-text">
			<area>
				<x>
					<value>32</value>
					<value>220</value>
					<value>220</value>
					<value>32</value>
				</x>
				<y>
					<value>280</value>
					<value>280</value>
					<value>356</value>
					<value>356</value>
				</y>
			</area>
			<modeconfig>
				<hwrconfiguration>
					<dict>
						<dictionary>en_US-ak-cur.res</dictionary>
						<linguistic>en_US-lk-text.res</linguistic>
						<locale>eng</locale>
					</dict>
					<orientationCorrection>true</orientationCorrection>
					<disableMultipleLines>false</disableMultipleLines>
					<wordCandidateListSize>10</wordCandidateListSize>
				</hwrconfiguration>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>		
		<modearea name="findings-sonography-left">
			<area>
				<x>
					<value>470</value>
					<value>730</value>
					<value>730</value>
					<value>470</value>
				</x>
				<y>
					<value>0</value>
					<value>0</value>
					<value>280</value>
					<value>280</value>
				</y>
			</area>
			<modeconfig>
				<shapedetection>
					<combineStrokes>false</combineStrokes>
					<enabled>true</enabled>
					<weightCircle>1.0</weightCircle>
					<weightCurvedArrow>0.0</weightCurvedArrow>
					<weightEllipticArc>0.0</weightEllipticArc>
					<weightEllispe>1.0</weightEllispe>
					<weightLine>1.0</weightLine>
					<weightParallelogram>0.0</weightParallelogram>
					<weightRectangle>1.0</weightRectangle>
					<weightRhombus>0.0</weightRhombus>
					<weightStroke>0.0</weightStroke>
					<weightTriangle>0.0</weightTriangle>
				</shapedetection>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>
		<modearea name="findings-sonography-left-text">
			<area>
				<x>
					<value>470</value>
					<value>730</value>
					<value>730</value>
					<value>470</value>
				</x>
				<y>
					<value>280</value>
					<value>280</value>
					<value>356</value>
					<value>356</value>
				</y>
			</area>
			<modeconfig>
				<hwrconfiguration>
					<dict>
						<dictionary>en_US-ak-cur.res</dictionary>
						<linguistic>en_US-lk-text.res</linguistic>
						<locale>eng</locale>
					</dict>
					<disableMultipleLines>false</disableMultipleLines>
					<wordCandidateListSize>10</wordCandidateListSize>
					<orientationCorrection>true</orientationCorrection>
				</hwrconfiguration>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>		
		<modearea name="findings-mammography-right-1">
			<area>
				<x>
					<value>32</value>
					<value>250</value>
					<value>250</value>
					<value>32</value>
				</x>
				<y>
					<value>357</value>
					<value>357</value>
					<value>487</value>
					<value>487</value>
				</y>
			</area>
			<modeconfig>
				<shapedetection>
					<combineStrokes>false</combineStrokes>
					<enabled>true</enabled>
					<weightCircle>1.0</weightCircle>
					<weightCurvedArrow>0.0</weightCurvedArrow>
					<weightEllipticArc>0.0</weightEllipticArc>
					<weightEllispe>1.0</weightEllispe>
					<weightLine>1.0</weightLine>
					<weightParallelogram>0.0</weightParallelogram>
					<weightRectangle>1.0</weightRectangle>
					<weightRhombus>0.0</weightRhombus>
					<weightStroke>0.0</weightStroke>
					<weightTriangle>0.0</weightTriangle>
				</shapedetection>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>		
	    <modearea name="findings-mammography-right-text-1">
			<area>
				<x>
					<value>32</value>
					<value>250</value>
					<value>250</value>
					<value>32</value>
				</x>
				<y>
					<value>487</value>
					<value>487</value>
					<value>515</value>
					<value>515</value>
				</y>
			</area>
			<modeconfig>
				<hwrconfiguration>
					<dict>
						<dictionary>en_US-ak-cur.res</dictionary>
						<linguistic>en_US-lk-text.res</linguistic>
						<locale>eng</locale>
					</dict>
					<orientationCorrection>true</orientationCorrection>
					<disableMultipleLines>false</disableMultipleLines>
					<wordCandidateListSize>10</wordCandidateListSize>
				</hwrconfiguration>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>		
		<modearea name="findings-mammography-right-2">
			<area>
				<x>
					<value>32</value>
					<value>250</value>
					<value>250</value>
					<value>32</value>
				</x>
				<y>
					<value>515</value>
					<value>515</value>
					<value>615</value>
					<value>615</value>
				</y>
			</area>
			<modeconfig>
				<shapedetection>
					<combineStrokes>false</combineStrokes>
					<enabled>true</enabled>
					<weightCircle>1.0</weightCircle>
					<weightCurvedArrow>0.0</weightCurvedArrow>
					<weightEllipticArc>0.0</weightEllipticArc>
					<weightEllispe>1.0</weightEllispe>
					<weightLine>1.0</weightLine>
					<weightParallelogram>0.0</weightParallelogram>
					<weightRectangle>1.0</weightRectangle>
					<weightRhombus>0.0</weightRhombus>
					<weightStroke>0.0</weightStroke>
					<weightTriangle>0.0</weightTriangle>
				</shapedetection>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>		
		<modearea name="findings-mammography-right-text-2">
			<area>
				<x>
					<value>32</value>
					<value>250</value>
					<value>250</value>
					<value>32</value>
				</x>
				<y>
					<value>615</value>
					<value>615</value>
					<value>810</value>
					<value>810</value>
				</y>
			</area>
			<modeconfig>
				<hwrconfiguration>
					<dict>
						<dictionary>en_US-ak-cur.res</dictionary>
						<linguistic>en_US-lk-text.res</linguistic>
						<locale>eng</locale>
					</dict>
					<orientationCorrection>true</orientationCorrection>
					<disableMultipleLines>false</disableMultipleLines>
					<wordCandidateListSize>10</wordCandidateListSize>
				</hwrconfiguration>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>		
		<modearea name="findings-mammography-left-1">
			<area>
				<x>
					<value>415</value>
					<value>700</value>
					<value>700</value>
					<value>415</value>
				</x>
				<y>
					<value>357</value>
					<value>357</value>
					<value>487</value>
					<value>487</value>
				</y>
			</area>
			<modeconfig>
				<shapedetection>
					<combineStrokes>false</combineStrokes>
					<enabled>true</enabled>
					<weightCircle>1.0</weightCircle>
					<weightCurvedArrow>0.0</weightCurvedArrow>
					<weightEllipticArc>0.0</weightEllipticArc>
					<weightEllispe>1.0</weightEllispe>
					<weightLine>1.0</weightLine>
					<weightParallelogram>0.0</weightParallelogram>
					<weightRectangle>1.0</weightRectangle>
					<weightRhombus>0.0</weightRhombus>
					<weightStroke>0.0</weightStroke>
					<weightTriangle>0.0</weightTriangle>
				</shapedetection>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>
		<modearea name="findings-mammography-left-text-1">
			<area>
				<x>
					<value>415</value>
					<value>700</value>
					<value>700</value>
					<value>415</value>
				</x>
				<y>
					<value>487</value>
					<value>487</value>
					<value>515</value>
					<value>515</value>
				</y>
			</area>
			<modeconfig>
				<hwrconfiguration>
					<dict>
						<dictionary>en_US-ak-cur.res</dictionary>
						<linguistic>en_US-lk-text.res</linguistic>
						<locale>eng</locale>
					</dict>
					<disableMultipleLines>false</disableMultipleLines>
					<wordCandidateListSize>10</wordCandidateListSize>
					<orientationCorrection>true</orientationCorrection>
				</hwrconfiguration>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>
		<modearea name="findings-mammography-left-2">
			<area>
				<x>
					<value>415</value>
					<value>700</value>
					<value>700</value>
					<value>415</value>
				</x>
				<y>
					<value>515</value>
					<value>515</value>
					<value>615</value>
					<value>615</value>
				</y>
			</area>
			<modeconfig>
				<shapedetection>
					<combineStrokes>false</combineStrokes>
					<enabled>true</enabled>
					<weightCircle>1.0</weightCircle>
					<weightCurvedArrow>0.0</weightCurvedArrow>
					<weightEllipticArc>0.0</weightEllipticArc>
					<weightEllispe>1.0</weightEllispe>
					<weightLine>1.0</weightLine>
					<weightParallelogram>0.0</weightParallelogram>
					<weightRectangle>1.0</weightRectangle>
					<weightRhombus>0.0</weightRhombus>
					<weightStroke>0.0</weightStroke>
					<weightTriangle>0.0</weightTriangle>
				</shapedetection>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>
		<modearea name="findings-mammography-left-text-2">
			<area>
				<x>
					<value>415</value>
					<value>700</value>
					<value>700</value>
					<value>415</value>
				</x>
				<y>
					<value>615</value>
					<value>615</value>
					<value>810</value>
					<value>810</value>
				</y>
			</area>
			<modeconfig>
				<hwrconfiguration>
					<dict>
						<dictionary>en_US-ak-cur.res</dictionary>
						<linguistic>en_US-lk-text.res</linguistic>
						<locale>eng</locale>
					</dict>
					<disableMultipleLines>false</disableMultipleLines>
					<wordCandidateListSize>10</wordCandidateListSize>
					<orientationCorrection>true</orientationCorrection>
				</hwrconfiguration>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>
		<modearea name="birads-1">
			<area>
				<x>
					<value>250</value>
					<value>415</value>
					<value>415</value>
					<value>250</value>
				</x>
				<y>
					<value>230</value>
					<value>230</value>
					<value>320</value>
					<value>320</value>
				</y>
			</area>
			<modeconfig>
				<shapedetection>
					<combineStrokes>false</combineStrokes>
					<enabled>true</enabled>
					<weightCircle>1.0</weightCircle>
					<weightCurvedArrow>0.0</weightCurvedArrow>
					<weightEllipticArc>0.0</weightEllipticArc>
					<weightEllispe>1.0</weightEllispe>
					<weightLine>0.0</weightLine>
					<weightParallelogram>0.0</weightParallelogram>
					<weightRectangle>1.0</weightRectangle>
					<weightRhombus>0.0</weightRhombus>
					<weightStroke>0.0</weightStroke>
					<weightTriangle>0.0</weightTriangle>
				</shapedetection>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>	
		<modearea name="birads-2">
			<area>
				<x>
					<value>250</value>
					<value>415</value>
					<value>415</value>
					<value>250</value>
				</x>
				<y>
					<value>710</value>
					<value>710</value>
					<value>820</value>
					<value>820</value>
				</y>
			</area>
			<modeconfig>
				<shapedetection>
					<combineStrokes>false</combineStrokes>
					<enabled>true</enabled>
					<weightCircle>1.0</weightCircle>
					<weightCurvedArrow>0.0</weightCurvedArrow>
					<weightEllipticArc>0.0</weightEllipticArc>
					<weightEllispe>1.0</weightEllispe>
					<weightLine>0.0</weightLine>
					<weightParallelogram>0.0</weightParallelogram>
					<weightRectangle>1.0</weightRectangle>
					<weightRhombus>0.0</weightRhombus>
					<weightStroke>0.0</weightStroke>
					<weightTriangle>0.0</weightTriangle>
				</shapedetection>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>			
		<modearea name="recommendation">
			<area>
				<x>
					<value>0</value>
					<value>700</value>
					<value>700</value>
					<value>0</value>
				</x>
				<y>
					<value>840</value>
					<value>840</value>
					<value>990</value>
					<value>990</value>
				</y>
			</area>
			<modeconfig>
				<hwrconfiguration>
					<dict>
						<dictionary>en_US-ak-cur.res</dictionary>
						<linguistic>en_US-lk-text.res</linguistic>
						<locale>eng</locale>
					</dict>
					<disableMultipleLines>false</disableMultipleLines>
					<wordCandidateListSize>10</wordCandidateListSize>
					<orientationCorrection>true</orientationCorrection>
				</hwrconfiguration>
				<trainingData>../touchandwrite-inputanalyser/src/main/resources/training-data/</trainingData>
			</modeconfig>
		</modearea>		
	</modeareas>
</profile>
